version: 2

models:
  - name: dim_track
    description: This table has basic information about a tracks

    columns:
      - name: track_id
        description: This is a unique identifier for a track
        tests:
          - unique
          - not_null

      - name: track_name
        description: Name of the track from track table

      - name: artist_name
        description: Name of the artist from track table

      - name: album_title
        description: Title of the album from artist table

      - name: genre_name
        description: Name of the genre from genre table

      - name: track_milliseconds
        description: Track duration in milliseconds from track table

      - name: track_bytes
        description: Track bytes from track table

      - name: media_type_name
        description: Name of the media type from media_type table